Re-structure bin/setup to avoid run-on commands

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,8 +1,20 @@
 #!/usr/bin/env bash
 
-hash foreman 2>/dev/null || {
-  echo >&2 'Could not find `foreman` executable. Please install it.';
-  exit 1;
+function main {
+  set -e
+
+  ensure_foreman_installed
+  cp .env.sample .env
+  bundle install
+  rake db:setup db:schema:load db:migrate
 }
 
-cp .env.sample .env && bundle install && rake db:setup db:schema:load db:migrate
+function ensure_foreman_installed {
+  hash foreman 2>/dev/null || {
+    echo >&2 'Could not find `foreman` executable. Please install it.';
+    false;
+  }
+}
+
+main
+
