Fix error in bin/setup when missing `foreman`
Back ticks are interpreted when in double quotes:

   $ bash -c 'echo "Missing `missing-command`"'
   bash: missing-command: command not found
   Missing

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 hash foreman 2>/dev/null || {
-  echo >&2 "Could not find `foreman` executable. Please install it.";
+  echo >&2 'Could not find `foreman` executable. Please install it.';
   exit 1;
 }
 
